name: "nix-build"
on:
  pull_request:
  push:
jobs:
  build:
    strategy:
      matrix:
        project_configuration_tool: ["your-project-name.cabal (cabal's default)", "package.yaml (hpack)"]
        add_executable_section: ["no", "yes"]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v12
    - uses: cachix/cachix-action@v8
      with:
        name: hs-nix-template
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build ci.nix --attr project_configuration_tool ${{ matrix.project_configuration_tool }} --attr add_executable_section ${{ matrix.add_executable_section }}
